# slab021 - AOS-CX Virtual.10.15.1020
slab021: {
  label: "slab021"
  type: "switch"
  role: "access_switch"
  model: "AOS-CX Virtual.10.15.1020"

  # Interface Configuration
  mgmt: {
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "dhcp"
    subnet_mask: ""
  }
  1/1/1: {
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "192.168.15.1"
    subnet_mask: "255.255.255.0"
  }
  1/1/2: {
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "192.168.16.1"
    subnet_mask: "255.255.255.0"
  }

  # Routing Configuration
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_router_id: "10.0.2.21"
  ospf_areas: "0.0.0.0"
}