# ISP1 - AT&T WAN Provider
isp1: {
  label: "ISP - AT&T"
  type: "wan"
  mgmt_ip: "10.2.1.1"
  
  # Provider Information
  provider_name: "AT&T"
  circuit_id: "ATT-MPLS-1234"
  bandwidth: "100Mbps"
  circuit_type: "MPLS"
  sla_class: "Business"
  bgp_asn: "64512"
  
  WAN1: {
    description: "Primary WAN Circuit"
    status: "up"
    bandwidth: "50Mbps"
    ip_address: "10.2.1.1"
    subnet_mask: "255.255.255.248"
  }
}