# rbigb2 - Secondary Core Router
rbigb2: {
  label: "rbigb2"
  type: "router"
  mgmt_ip: "10.2.1.11"
  
  # Routing Information
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "0,1"
  ospf_router_id: "10.2.1.11"
  bgp_enabled: "true"
  bgp_asn: "65001"
  bgp_router_id: "10.2.1.11"
  routing_table_count: "42"
  default_gateway: "10.2.1.1"
  vrrp_status: "standby"
  vrrp_group: "1"
  vrrp_priority: "100"
  hsrp_enabled: "false"
  
  # Static Routes
  static_routes: "0.0.0.0/0 via 10.2.1.1, 192.168.200.0/24 via 10.2.1.10"
  
  GigabitEthernet0/0/0: {
    description: "Verizon Uplink"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "50Mbps"
    ip_address: "10.2.1.10"
    subnet_mask: "255.255.255.248"
    ospf_area: "0"
    ospf_cost: "100"
    ospf_network_type: "point-to-point"
    bgp_neighbor: "10.2.1.9"
    bgp_neighbor_asn: "64513"
    bgp_session_type: "eBGP"
  }
  
  GigabitEthernet0/0/1: {
    description: "rbigb1.gi0/0/1"
    switchport_mode: "routed"
    native_vlan: 
    allowed_vlans: 
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.2.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
    bgp_neighbor: "10.2.2.1"
    bgp_neighbor_asn: "65001"
    bgp_session_type: "iBGP"
  }
  
  GigabitEthernet0/0/2: {
    description: "sbigb2.1/0/1"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.4.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "5"
  }
}