# sbigb2 - Secondary Distribution Switch
sbigb2: {
  label: "sbigb2"
  type: "switch"
  mgmt_ip: "10.2.1.31"
  
  # Layer 3 Switch Routing Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.31"
  routing_table_count: "25"
  dhcp_relay_enabled: "true"
  vrrp_groups: "2"
  
  vlan30: {
    vlan_id: "30"
    ip_address: "10.0.30.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
    vrrp_group: "30"
    vrrp_priority: "110"
    vrrp_virtual_ip: "10.0.30.254"
  }
  
  vlan40: {
    vlan_id: "40"
    ip_address: "10.0.40.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
    vrrp_group: "40"
    vrrp_priority: "110"
    vrrp_virtual_ip: "10.0.40.254"
  }
  
  vlan200: {
    vlan_id: "200"
    ip_address: "10.0.200.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    description: "Management VLAN"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/0/1: {
    description: "rbigb2.gi0/0/2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,30,40,50,200-250"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/3: {
    description: "wlc2.0/0/1"
    switchport_mode: "access"
    access_vlan: 200
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/4: {
    description: "wlc2.0/0/2"
    switchport_mode: "access"
    access_vlan: 200
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/7: {
    description: "sbigb1.1/0/7"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "1Gbps"
    channel_group: "1"
    channel_group_mode: "active"
  }
  
  1/0/8: {
    description: "sbigb1.1/0/8"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "1Gbps"
    channel_group: "1"
    channel_group_mode: "active"
  }
  
  Port-channel1: {
    description: "Inter-switch link to sbigb1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "2Gbps"
    protocol: "LACP"
    members: "1/0/7,1/0/8"
    load_balancing: "src-dst-ip"
  }
  
  1/1/51: {
    description: "sbigb101.1/1/50"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.11.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/52: {
    description: "sbigb102.1/1/50"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.13.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/53: {
    description: "sbigb111.1/1/50"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.15.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
}