# sbigb102 - Access Switch 102
sbigb102: {
  label: "sbigb102"
  type: "switch"
  mgmt_ip: "10.2.1.102"
  
  # Layer 3 Access Switch Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.102"
  routing_table_count: "15"
  dhcp_relay_enabled: "true"
  
  # Switch VLANs
  vlan60: {
    vlan_id: "60"
    ip_address: "10.0.60.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  vlan61: {
    vlan_id: "61"
    ip_address: "10.0.61.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/1/49: {
    description: "sbigb1.1/1/52"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.12.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/50: {
    description: "sbigb2.1/1/52"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.13.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/0/1: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 60
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/2: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 61
    status: "up"
    bandwidth: "1Gbps"
  }
}