# Datacenter Network Topology - Complete Connection Data
# Company naming convention: (type)(site)(number)
# Interface configurations included

# Device Definitions with Interface Configurations
rdc1: {
  label: "rdc1"
  type: "router"
  mgmt_ip: "10.1.1.10"
  
  GigabitEthernet0/0/1: {
    description: "WAN Uplink to sdc1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
}

rdc2: {
  label: "rdc2"
  type: "router"
  mgmt_ip: "10.1.1.11"
  
  GigabitEthernet0/0/1: {
    description: "WAN Uplink to sdc2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
}

rdc-inet1: {
  label: "rdc-inet1"
  type: "router"
  mgmt_ip: "10.1.1.12"
  
  GigabitEthernet0/0/1: {
    description: "Internet Feed to fdc-inet1"
    switchport_mode: "access"
    access_vlan: 999
    status: "up"
    bandwidth: "1Gbps"
  }
}

rdc-inet2: {
  label: "rdc-inet2"
  type: "router" 
  mgmt_ip: "10.1.1.13"
  
  GigabitEthernet0/0/1: {
    description: "Internet Feed to fdc-inet1b"
    switchport_mode: "access"
    access_vlan: 999
    status: "up"
    bandwidth: "1Gbps"
  }
}

fdc-inet1: {
  label: "fdc-inet1"
  type: "firewall"
  mgmt_ip: "10.1.1.20"
  
  ethernet1/1: {
    description: "Internet Feed from rdc-inet1"
    switchport_mode: "access"
    access_vlan: 999
    status: "up"
    bandwidth: "1Gbps"
  }
  
  ethernet1/2: {
    description: "Firewall Trust to sdc1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
}

fdc-inet1b: {
  label: "fdc-inet1b"
  type: "firewall"
  mgmt_ip: "10.1.1.21"
  
  ethernet1/1: {
    description: "Internet Feed from rdc-inet2"
    switchport_mode: "access"
    access_vlan: 999
    status: "up"
    bandwidth: "1Gbps"
  }
  
  ethernet1/2: {
    description: "Firewall Trust to sdc2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
}

sdc1: {
  label: "sdc1"
  type: "switch"
  mgmt_ip: "10.1.1.30"
  
  1/0/47: {
    description: "WAN Uplink from rdc1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/46: {
    description: "Firewall Trust from fdc-inet1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/48: {
    description: "Core ISL to sdc2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "all"
    status: "up"
    bandwidth: "10Gbps"
  }
  
  1/0/24: {
    description: "Server Uplink to sdc3"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-300"
    status: "up"
    bandwidth: "10Gbps"
  }
  
  1/0/12: {
    description: "WLC Management to wdc1"
    switchport_mode: "access"
    access_vlan: 100
    status: "up"
    bandwidth: "1Gbps"
  }
}

sdc2: {
  label: "sdc2"
  type: "switch"
  mgmt_ip: "10.1.1.31"
  
  1/0/47: {
    description: "WAN Uplink from rdc2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/46: {
    description: "Firewall Trust from fdc-inet1b"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/48: {
    description: "Core ISL to sdc1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "all"
    status: "up"
    bandwidth: "10Gbps"
  }
  
  1/0/24: {
    description: "Server Uplink to sdc4"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-300"
    status: "up"
    bandwidth: "10Gbps"
  }
  
  1/0/12: {
    description: "WLC Management to wdc2"
    switchport_mode: "access"
    access_vlan: 100
    status: "up"
    bandwidth: "1Gbps"
  }
}

sdc3: {
  label: "sdc3"
  type: "switch"
  mgmt_ip: "10.1.1.40"
  
  1/0/48: {
    description: "Server Uplink from sdc1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-300"
    status: "up"
    bandwidth: "10Gbps"
  }
  
  1/0/47: {
    description: "Server ISL to sdc4"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-300"
    status: "up"
    bandwidth: "10Gbps"
  }
}

sdc4: {
  label: "sdc4"
  type: "switch"
  mgmt_ip: "10.1.1.41"
  
  1/0/48: {
    description: "Server Uplink from sdc2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-300"
    status: "up"
    bandwidth: "10Gbps"
  }
  
  1/0/47: {
    description: "Server ISL to sdc3"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-300"
    status: "up"
    bandwidth: "10Gbps"
  }
}

wdc1: {
  label: "wdc1"
  type: "wireless_controller"
  mgmt_ip: "10.1.1.50"
  
  port1: {
    description: "Management link to sdc1"
    status: "up"
    bandwidth: "1Gbps"
    vlan: 100
  }
}

wdc2: {
  label: "wdc2"
  type: "wireless_controller"
  mgmt_ip: "10.1.1.51"
  
  port1: {
    description: "Management link to sdc2"
    status: "up"
    bandwidth: "1Gbps"
    vlan: 100
  }
}

# Connection Topology - Simple References
rdc1.GigabitEthernet0/0/1 -> sdc1.1/0/47
rdc2.GigabitEthernet0/0/1 -> sdc2.1/0/47
rdc-inet1.GigabitEthernet0/0/1 -> fdc-inet1.ethernet1/1
rdc-inet2.GigabitEthernet0/0/1 -> fdc-inet1b.ethernet1/1
fdc-inet1.ethernet1/2 -> sdc1.1/0/46
fdc-inet1b.ethernet1/2 -> sdc2.1/0/46
sdc1.1/0/48 -> sdc2.1/0/48
sdc1.1/0/24 -> sdc3.1/0/48
sdc2.1/0/24 -> sdc4.1/0/48
sdc3.1/0/47 -> sdc4.1/0/47
sdc1.1/0/12 -> wdc1.port1
sdc2.1/0/12 -> wdc2.port1