# Branch Site Network Topology - Complete Connection Data with Routing
# Company naming convention: (type)(site)(number)
# Interface configurations and routing information included

# Device Definitions with Interface Configurations and Routing

# External/WAN Connections
isp1: {
  label: "ISP - AT&T"
  type: "wan"
  mgmt_ip: "10.2.1.1"
  
  # Provider Information
  provider_name: "AT&T"
  circuit_id: "ATT-MPLS-1234"
  bandwidth: "100Mbps"
  circuit_type: "MPLS"
  sla_class: "Business"
  bgp_asn: "64512"
  
  WAN1: {
    description: "Primary WAN Circuit"
    status: "up"
    bandwidth: "50Mbps"
    ip_address: "10.2.1.1"
    subnet_mask: "255.255.255.248"
  }
}
isp2: {
  label: "ISP - Verizon"
  type: "wan"
  mgmt_ip: "10.2.1.9"
  
  # Provider Information
  provider_name: "Verizon"
  circuit_id: "VZ-MPLS-1234"
  bandwidth: "100Mbps"
  circuit_type: "MPLS"
  sla_class: "Business"
  bgp_asn: "64513"  
  WAN1: {
    description: "Secondary WAN Circuit"
    status: "up"
    bandwidth: "50Mbps"
    ip_address: "10.2.1.9"
    subnet_mask: "255.255.255.248"
  }
}
rbigb1: {
  label: "rbigb1"
  type: "router"
  mgmt_ip: "10.2.1.10"
  
  # Routing Information
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "0,1"
  ospf_router_id: "10.2.1.10"
  bgp_enabled: "true"
  bgp_asn: "65001"
  bgp_router_id: "10.2.1.10"
  routing_table_count: "45"
  default_gateway: "10.2.1.1"
  vrrp_status: "active"
  vrrp_group: "1"
  vrrp_priority: "110"
  hsrp_enabled: "false"
  
  # Static Routes
  static_routes: "0.0.0.0/0 via 10.2.1.1, 192.168.100.0/24 via 10.2.1.11"
  
  GigabitEthernet0/0/0: {
    description: "AT&T Uplink"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "50Mbps"
    ip_address: "10.2.1.2"
    subnet_mask: "255.255.255.248"
    ospf_area: "0"
    ospf_cost: "100"
    ospf_network_type: "point-to-point"
    bgp_neighbor: "10.2.1.1"
    bgp_neighbor_asn: "64512"
    bgp_session_type: "eBGP"
  }
  
  GigabitEthernet0/0/1: {
    description: "rbigb2.gi0/0/1"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.2.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
    bgp_neighbor: "10.2.2.2"
    bgp_neighbor_asn: "65001"
    bgp_session_type: "iBGP"
  }
  
  GigabitEthernet0/0/2: {
    description: "sbigb1.1/0/1"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.3.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "5"
  }
}

rbigb2: {
  label: "rbigb2"
  type: "router"
  mgmt_ip: "10.2.1.11"
  
  # Routing Information
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "0,1"
  ospf_router_id: "10.2.1.11"
  bgp_enabled: "true"
  bgp_asn: "65001"
  bgp_router_id: "10.2.1.11"
  routing_table_count: "42"
  default_gateway: "10.2.1.1"
  vrrp_status: "standby"
  vrrp_group: "1"
  vrrp_priority: "100"
  hsrp_enabled: "false"
  
  # Static Routes
  static_routes: "0.0.0.0/0 via 10.2.1.1, 192.168.200.0/24 via 10.2.1.10"
  
  GigabitEthernet0/0/0: {
    description: "Verizon Uplink"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "50Mbps"
    ip_address: "10.2.1.10"
    subnet_mask: "255.255.255.248"
    ospf_area: "0"
    ospf_cost: "100"
    ospf_network_type: "point-to-point"
    bgp_neighbor: "10.2.1.9"
    bgp_neighbor_asn: "64513"
    bgp_session_type: "eBGP"
  }
  
  GigabitEthernet0/0/1: {
    description: "rbigb1.gi0/0/1"
    switchport_mode: "routed"
    native_vlan: 
    allowed_vlans: 
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.2.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
    bgp_neighbor: "10.2.2.1"
    bgp_neighbor_asn: "65001"
    bgp_session_type: "iBGP"
  }
  
  GigabitEthernet0/0/2: {
    description: "sbigb2.1/0/1"
    switchport_mode: "routed"
    native_vlan:
    allowed_vlans:
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.4.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "5"
  }
}

sbigb1: {
  label: "sbigb1"
  type: "switch"
  mgmt_ip: "10.2.1.30"
  
  # Layer 3 Switch Routing Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.30"
  routing_table_count: "25"
  dhcp_relay_enabled: "true"
  vrrp_groups: "2"
  
  vlan10: {
    vlan_id: "10"
    ip_address: "10.0.10.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
    vrrp_group: "10"
    vrrp_priority: "110"
    vrrp_virtual_ip: "10.0.10.254"
  }
  
  vlan20: {
    vlan_id: "20"
    ip_address: "10.0.20.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
    vrrp_group: "20"
    vrrp_priority: "110"
    vrrp_virtual_ip: "10.0.20.254"
  }
  
  vlan100: {
    vlan_id: "100"
    ip_address: "10.0.100.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    description: "Management VLAN"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/0/1: {
    description: "rbigb1.gi0/0/2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,100-200"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/3: {
    description: "wlc1.0/0/1"
    switchport_mode: "access"
    access_vlan: 100
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/4: {
    description: "wlc1.0/0/2"
    switchport_mode: "access"
    access_vlan: 100
    status: "up"
    bandwidth: "1Gbps"
  }

  1/0/7: {
    description: "sbigb2.1/0/7"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "1Gbps"
    channel_group: "1"
    channel_group_mode: "active"
  }
  
  1/0/8: {
    description: "sbigb2.1/0/8"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "1Gbps"
    channel_group: "1"
    channel_group_mode: "active"
  }
  
  Port-channel1: {
    description: "Inter-switch link to sbigb2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "2Gbps"
    protocol: "LACP"
    members: "1/0/7,1/0/8"
    load_balancing: "src-dst-ip"
  }
  
  1/1/51: {
    description: "sbigb101.1/1/49"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.10.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/52: {
    description: "sbigb102.1/1/49"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.12.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/53: {
    description: "sbigb111.1/1/49"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.14.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
}

sbigb2: {
  label: "sbigb2"
  type: "switch"
  mgmt_ip: "10.2.1.31"
  
  # Layer 3 Switch Routing Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.31"
  routing_table_count: "25"
  dhcp_relay_enabled: "true"
  vrrp_groups: "2"
  
  vlan30: {
    vlan_id: "30"
    ip_address: "10.0.30.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
    vrrp_group: "30"
    vrrp_priority: "110"
    vrrp_virtual_ip: "10.0.30.254"
  }
  
  vlan40: {
    vlan_id: "40"
    ip_address: "10.0.40.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
    vrrp_group: "40"
    vrrp_priority: "110"
    vrrp_virtual_ip: "10.0.40.254"
  }
  
  vlan200: {
    vlan_id: "200"
    ip_address: "10.0.200.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    description: "Management VLAN"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/0/1: {
    description: "rbigb2.gi0/0/2"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,30,40,50,200-250"
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/3: {
    description: "wlc2.0/0/1"
    switchport_mode: "access"
    access_vlan: 200
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/4: {
    description: "wlc2.0/0/2"
    switchport_mode: "access"
    access_vlan: 200
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/7: {
    description: "sbigb1.1/0/7"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "1Gbps"
    channel_group: "1"
    channel_group_mode: "active"
  }
  
  1/0/8: {
    description: "sbigb1.1/0/8"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "1Gbps"
    channel_group: "1"
    channel_group_mode: "active"
  }
  
  Port-channel1: {
    description: "Inter-switch link to sbigb1"
    switchport_mode: "trunk"
    native_vlan: 1
    allowed_vlans: "1,10,20,30,40,100,200"
    status: "up"
    bandwidth: "2Gbps"
    protocol: "LACP"
    members: "1/0/7,1/0/8"
    load_balancing: "src-dst-ip"
  }
  
  1/1/51: {
    description: "sbigb101.1/1/50"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.11.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/52: {
    description: "sbigb102.1/1/50"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.13.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/53: {
    description: "sbigb111.1/1/50"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.15.1"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
}

sbigb101: {
  label: "sbigb101"
  type: "switch"
  mgmt_ip: "10.2.1.101"
  
  # Layer 3 Access Switch Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.101"
  routing_table_count: "15"
  dhcp_relay_enabled: "true"
  
  # Switch VLANs
  vlan50: {
    vlan_id: "50"
    ip_address: "10.0.50.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  vlan51: {
    vlan_id: "51"
    ip_address: "10.0.51.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/1/49: {
    description: "sbigb1.1/1/51"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.10.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/50: {
    description: "sbigb2.1/1/51"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.11.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/0/1: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 50
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/2: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 51
    status: "up"
    bandwidth: "1Gbps"
  }
}

sbigb102: {
  label: "sbigb102"
  type: "switch"
  mgmt_ip: "10.2.1.102"
  
  # Layer 3 Access Switch Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.102"
  routing_table_count: "15"
  dhcp_relay_enabled: "true"
  
  # Switch VLANs
  vlan60: {
    vlan_id: "60"
    ip_address: "10.0.60.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  vlan61: {
    vlan_id: "61"
    ip_address: "10.0.61.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/1/49: {
    description: "sbigb1.1/1/52"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.12.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/50: {
    description: "sbigb2.1/1/52"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.13.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/0/1: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 60
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/2: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 61
    status: "up"
    bandwidth: "1Gbps"
  }
}

sbigb111: {
  label: "sbigb111"
  type: "switch"
  mgmt_ip: "10.2.1.111"
  
  # Layer 3 Access Switch Information
  ip_routing_enabled: "true"
  ospf_enabled: "true"
  ospf_process_id: "1"
  ospf_areas: "1"
  ospf_router_id: "10.2.1.111"
  routing_table_count: "15"
  dhcp_relay_enabled: "true"
  
  # Switch VLANs
  vlan70: {
    vlan_id: "70"
    ip_address: "10.0.70.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  vlan71: {
    vlan_id: "71"
    ip_address: "10.0.71.1"
    subnet_mask: "255.255.255.0"
    status: "up"
    helper_address: "10.1.1.10"
    ospf_area: "1"
    ospf_cost: "1"
  }
  
  1/1/49: {
    description: "sbigb1.1/1/53"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.14.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/1/50: {
    description: "sbigb2.1/1/53"
    switchport_mode: "routed"
    status: "up"
    bandwidth: "1Gbps"
    ip_address: "10.2.15.2"
    subnet_mask: "255.255.255.252"
    ospf_area: "1"
    ospf_cost: "10"
    ospf_network_type: "point-to-point"
  }
  
  1/0/1: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 70
    status: "up"
    bandwidth: "1Gbps"
  }
  
  1/0/2: {
    description: "Access port for devices"
    switchport_mode: "access"
    access_vlan: 71
    status: "up"
    bandwidth: "1Gbps"
  }
}

wbigb1: {
  label: "wbigb1"
  type: "wireless_controller"
  mgmt_ip: "10.2.1.50"
  
  # Wireless Controller Information
  controller_status: "active"
  aps_connected: "12"
  total_clients: "147"
  licenses_used: "12"
  licenses_available: "50"
  firmware_version: "8.10.162.0"
  
  # Wireless Networks
  ssid_count: "3"
  ssids: "Corporate-WiFi,Guest-WiFi,IoT-WiFi"
  
  0/0/1: {
    description: "sbigb1.1/0/3"
    status: "up"
    bandwidth: "1Gbps"
    vlan: 100
  }
  
  0/0/2: {
    description: "sbigb1.1/0/4"
    status: "up"
    bandwidth: "1Gbps"
    vlan: 100
  }
}

wbigb2: {
  label: "wbigb2"
  type: "wireless_controller"
  mgmt_ip: "10.2.1.51"
  
  # Wireless Controller Information
  controller_status: "standby"
  aps_connected: "0"
  total_clients: "0"
  licenses_used: "0"
  licenses_available: "50"
  firmware_version: "8.10.162.0"
  
  # Wireless Networks
  ssid_count: "3"
  ssids: "Corporate-WiFi,Guest-WiFi,IoT-WiFi"
  
  0/0/1: {
    description: "sbigb2.1/0/3"
    status: "up"
    bandwidth: "1Gbps"
    vlan: 100
  }
  
  0/0/2: {
    description: "sbigb2.1/0/4"
    status: "up"
    bandwidth: "1Gbps"
    vlan: 100
  }
}

# Routing Table Entries (Optional - for detailed routing display)
routing_table: {
  rbigb1_routes: {
    "0.0.0.0/0": {
      next_hop: "10.2.1.1"
      interface: "GigabitEthernet0/0/0"
      protocol: "static"
      metric: "1"
    }
    "10.0.10.0/24": {
      next_hop: "10.2.3.2"
      interface: "GigabitEthernet0/0/2"
      protocol: "ospf"
      metric: "6"
    }
    "10.0.20.0/24": {
      next_hop: "10.2.3.2"
      interface: "GigabitEthernet0/0/2"
      protocol: "ospf"
      metric: "6"
    }
  }
  
  rbigb2_routes: {
    "0.0.0.0/0": {
      next_hop: "10.2.1.1"
      interface: "GigabitEthernet0/0/0"
      protocol: "static"
      metric: "1"
    }
    "10.0.30.0/24": {
      next_hop: "10.2.4.2"
      interface: "GigabitEthernet0/0/2"
      protocol: "ospf"
      metric: "6"
    }
    "10.0.40.0/24": {
      next_hop: "10.2.4.2"
      interface: "GigabitEthernet0/0/2"
      protocol: "ospf"
      metric: "6"
    }
    "10.0.10.0/24": {
      next_hop: "10.2.2.1"
      interface: "GigabitEthernet0/0/1"
      protocol: "ospf"
      metric: "11"
    }
    "10.0.20.0/24": {
      next_hop: "10.2.2.1"
      interface: "GigabitEthernet0/0/1"
      protocol: "ospf"
      metric: "11"
    }
  }
}

# Connection Topology - Simple References

# WAN Connections
rbigb1.GigabitEthernet0/0/0 -> isp1.WAN1
rbigb2.GigabitEthernet0/0/0 -> isp2.WAN1

# Internal Connections
rbigb1.GigabitEthernet0/0/1 -> rbigb2.GigabitEthernet0/0/1
rbigb1.GigabitEthernet0/0/2 -> sbigb1.1/0/1
rbigb2.GigabitEthernet0/0/2 -> sbigb2.1/0/1
sbigb1.1/0/3 -> wbigb1.0/0/1
sbigb1.1/0/4 -> wbigb1.0/0/2
sbigb2.1/0/3 -> wbigb2.0/0/1
sbigb2.1/0/4 -> wbigb2.0/0/2
sbigb1.Port-channel1 -> sbigb2.Port-channel1

# Access Layer Connections (Dual-homed to both core switches)
sbigb1.1/1/51 -> sbigb101.1/1/49
sbigb2.1/1/51 -> sbigb101.1/1/50
sbigb1.1/1/52 -> sbigb102.1/1/49
sbigb2.1/1/52 -> sbigb102.1/1/50
sbigb1.1/1/53 -> sbigb111.1/1/49
sbigb2.1/1/53 -> sbigb111.1/1/50